import os
print("\033c\033[47;30m\nget me a .ss stringscript file to view")
a=input().strip()
f1=open(a,"r")
ff=f1.read()
f1.close()
ff=ff.replace("\\\\h1","<h1>")
ff=ff.replace("\\\\h2","<h2>")
ff=ff.replace("\\\\h3","<h3>")
ff=ff.replace("\\\\h4","<h4>")
ff=ff.replace("\\\\h5","<h5>")
ff=ff.replace("\n","<br>")
ff=ff.replace("\r","<br>")
ff=ff.replace("\\\\a","<a>")
ff=ff.replace("\\\\p","<p>")
ff=ff.replace("\\\\-p","</p>")
ff=ff.replace("\\\\-h1","</h1>")
ff=ff.replace("\\\\-h2","</h2>")
ff=ff.replace("\\\\-h3","</h3>")
ff=ff.replace("\\\\-h4","</h4>")
ff=ff.replace("\\\\-h5","</h5>")
ff=ff.replace("\\\\b","<b>")
ff=ff.replace("\\\\-b","</b>")
f1=open("/tmp/html.html","w")
f1.write(ff)
f1.close()
os.system("xdg-open /tmp/html.html")